db.bol.insert(
  {
  "BOLHeader" : {
    "objectId" : "385_359329_17181",
    "objectType" : "BOL_HEADER",
    "bolContractVersion" : "V4.0",
    "developmentStyleIdentifier" : "96059",
    "developmentColorwayIdentifier" : "359329",
    "colorwayName" : "359329-WHITE/PR PLTNM-PR PLTNM-WHITE-100-SU19",
    "sourcingConfigurationIdentifier" : "17181",
    "sourcingConfigurationName" : "VO-FENG TAY ENTERPRISES CO. LTD.",
    "billoflaborIdentifier" : "385",
    "billoflaborName" : "001 : 385",
    "billoflaborVersionNumber" : "A.24",
    "billoflaborStatusIndicator" : "1",
    "createTimestamp" : "2018-08-12 11:08:32.0",
    "changeTimestamp" : "2022-06-29 23:33:21.0",
    "createdBy" : "wcadmin",
    "modifiedBy" : "Srikanth Chittapragada",
    "styleNumber" : "AV3042",
    "styleName" : "AIR FORCE 1 FLYKNIT 2.0 - AV3042",
    "modelIdentifier" : "144582",
    "gender" : "01",
    "age" : "10",
    "productId" : "3507138",
    "productCode" : "AV3042-100"
  },
  "BOLData" : [ {
    "billoflaborLineSortingSequence" : "1",
    "billoflaborSectionIdentifier" : "1",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "Test",
    "laborProcessIdentifier" : "152",
    "laborItemPlaceholderDescription" : "Upper Construction-Attaching-Heat Gun",
    "billoflaborLineItemComments" : "P11 - 5,S18x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "3",
    "billoflaborSectionIdentifier" : "1",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "153",
    "laborItemPlaceholderDescription" : "Upper Construction-Attaching-Heat Press",
    "billoflaborLineItemComments" : "P11 - 5,S19x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "5",
    "billoflaborSectionIdentifier" : "1",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "154",
    "laborItemPlaceholderDescription" : "Upper Construction-Attaching-Hot Melt",
    "billoflaborLineItemComments" : "P5,S1x1 ; P11 - 2,S5x1,S7x1 ; P11 - 3,S12x1 ; P11 - 4,S13x3 ; P11 - 6,S23x1 ; P11 - 7,S27x1,S28x1 ; P11 - 8,S32x1 ; P11 - 9,S33x1,S36x1 ; P11 - 10,S40x1 ; P11 - 11,S43x1 ; P11 - 12,S47x1 ; P11 - 13,S52x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "17",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "7",
    "billoflaborSectionIdentifier" : "1",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "155",
    "laborItemPlaceholderDescription" : "Upper Construction-Attaching-Lacing",
    "billoflaborLineItemComments" : "P11 - 14,S56x18 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "18",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "9",
    "billoflaborSectionIdentifier" : "1",
    "partNameIdentifier" : "1839",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "164",
    "laborItemPlaceholderDescription" : "Upper Construction-Shaping-Punching",
    "billoflaborLineItemComments" : "P11 - 10,S39x2 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "2",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "11",
    "billoflaborSectionIdentifier" : "1",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "162",
    "laborItemPlaceholderDescription" : "Upper Construction-Shaping-Fold/Turn",
    "billoflaborLineItemComments" : "P11 - 9,S35x1 ; P11 - 12,S46x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "2",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "13",
    "billoflaborSectionIdentifier" : "1",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "163",
    "laborItemPlaceholderDescription" : "Upper Construction-Shaping-Hammering",
    "billoflaborLineItemComments" : "P11 - 6,S22x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "15",
    "billoflaborSectionIdentifier" : "1",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "165",
    "laborItemPlaceholderDescription" : "Upper Construction-Sockliner Making-Die Cut Sockliner",
    "billoflaborLineItemComments" : "P17,S2x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "17",
    "billoflaborSectionIdentifier" : "1",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "167",
    "laborItemPlaceholderDescription" : "Upper Construction-Stitching-Closed seam ≤20cm",
    "billoflaborLineItemComments" : "P11 - 11,S42x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "19",
    "billoflaborSectionIdentifier" : "1",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "168",
    "laborItemPlaceholderDescription" : "Upper Construction-Stitching-Computer w/ Fixed Jig",
    "billoflaborLineItemComments" : "P9 - 1x2 ; P9 - 2x1 ; P9 - 3x1 ; P9 - 4x3 ; P9 - 5x1 ; P9 - 6x2 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "10",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "21",
    "billoflaborSectionIdentifier" : "1",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "169",
    "laborItemPlaceholderDescription" : "Upper Construction-Stitching-Computer w/ Pallet",
    "billoflaborLineItemComments" : "P9 - 1x32 ; P9 - 2x14 ; P9 - 3x4 ; P9 - 5x5 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "55",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "23",
    "billoflaborSectionIdentifier" : "1",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "173",
    "laborItemPlaceholderDescription" : "Upper Construction-Stitching-Medium (20-40cm)",
    "billoflaborLineItemComments" : "P11 - 8,S30x1,S31x1 ; P11 - 14,S54x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "3",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "25",
    "billoflaborSectionIdentifier" : "1",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "174",
    "laborItemPlaceholderDescription" : "Upper Construction-Stitching-Short (<20cm)",
    "billoflaborLineItemComments" : "P11 - 5,S20x1 ; P11 - 6,S21x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "2",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "1",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "196",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Pair Matching",
    "billoflaborLineItemComments" : "P3x2 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "3",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "1658",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "196",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Pair Matching",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "5",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "197",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Part Aligned - Large",
    "billoflaborLineItemComments" : "P3x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "7",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "1839",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "202",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Synthetic/Textile 4 Layers",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "9",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "1658",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "199",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Part Aligned - Small",
    "billoflaborLineItemComments" : "P3x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "11",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "103",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "201",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Synthetic/Textile 2 Layers",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "2",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "13",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "2049",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "202",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Synthetic/Textile 4 Layers",
    "billoflaborLineItemComments" : "P2 - 1,S2x2,S3x1,S4x1 ; P2 - 2,S5x2,S6x1,S7x1 ; P2 - 3,S9x1,S10x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "2",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "15",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "215734",
    "laborItemPlaceholderDescription" : "Upper Preparation--Placeholder",
    "billoflaborLineItemComments" : "P11 - 1,S4x1, UPPER process",
    "billoflaborObservedMinutes" : "0.433",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "17",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "1782",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "202",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Synthetic/Textile 4 Layers",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "19",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "891",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "202",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Synthetic/Textile 4 Layers",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "2",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "21",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "768",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "202",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Synthetic/Textile 4 Layers",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "23",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "2469",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "202",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Synthetic/Textile 4 Layers",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "25",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "985",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "202",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Synthetic/Textile 4 Layers",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "27",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "1247",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "202",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Synthetic/Textile 4 Layers",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "29",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "1481",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "203",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Synthetic/Textile 6 Layers",
    "billoflaborLineItemComments" : "P2 - 2,S8x1 ; P2 - 4,S13x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "31",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "183",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "203",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Synthetic/Textile 6 Layers",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "33",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "2326",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "204",
    "laborItemPlaceholderDescription" : "Upper Preparation-Cutting-Synthetic/Textile 8 Layers",
    "billoflaborLineItemComments" : "P2 - 1,S1x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "35",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "183",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "205",
    "laborItemPlaceholderDescription" : "Upper Preparation-Edge Treatment-Semi Auto Folding by Machine ≤20cm",
    "billoflaborLineItemComments" : "P7x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "37",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "2049",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "209",
    "laborItemPlaceholderDescription" : "Upper Preparation-Edge Treatment-Trimming Upper",
    "billoflaborLineItemComments" : "P11 - 5,S17x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "39",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "1782",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "212",
    "laborItemPlaceholderDescription" : "Upper Preparation-Skiving-Manual Skiving",
    "billoflaborLineItemComments" : "P6,S1x1,S2x2,S3x1,S4x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "41",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "891",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "212",
    "laborItemPlaceholderDescription" : "Upper Preparation-Skiving-Manual Skiving",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "2",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "43",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "985",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "212",
    "laborItemPlaceholderDescription" : "Upper Preparation-Skiving-Manual Skiving",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "45",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "1247",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "212",
    "laborItemPlaceholderDescription" : "Upper Preparation-Skiving-Manual Skiving",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "47",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "On Upper side",
    "laborProcessIdentifier" : "216",
    "laborItemPlaceholderDescription" : "Upper Preparation-Stitch Marking-Stitch Marking - Pen",
    "billoflaborLineItemComments" : "P8 - 1,S1x1,S2x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "49",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "2",
    "billoflaborLineItemDescription" : "on Back Side",
    "laborProcessIdentifier" : "216",
    "laborItemPlaceholderDescription" : "Upper Preparation-Stitch Marking-Stitch Marking - Pen",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "51",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "1782",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "217",
    "laborItemPlaceholderDescription" : "Upper Preparation-Stitch Marking-Stitch Marking - Screen",
    "billoflaborLineItemComments" : "P8 - 1,S3x1,S4x1,S5x1,S6x1,S7x1,S8x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "53",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "768",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "217",
    "laborItemPlaceholderDescription" : "Upper Preparation-Stitch Marking-Stitch Marking - Screen",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "55",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "1658",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "217",
    "laborItemPlaceholderDescription" : "Upper Preparation-Stitch Marking-Stitch Marking - Screen",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "57",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "28",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "217",
    "laborItemPlaceholderDescription" : "Upper Preparation-Stitch Marking-Stitch Marking - Screen",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "59",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "1481",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "217",
    "laborItemPlaceholderDescription" : "Upper Preparation-Stitch Marking-Stitch Marking - Screen",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "61",
    "billoflaborSectionIdentifier" : "2",
    "partNameIdentifier" : "976",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "217",
    "laborItemPlaceholderDescription" : "Upper Preparation-Stitch Marking-Stitch Marking - Screen",
    "billoflaborLineItemComments" : "",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "1",
    "billoflaborSectionIdentifier" : "3",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "181",
    "laborItemPlaceholderDescription" : "Upper Embellishment-HF Welding-HF Welding",
    "billoflaborLineItemComments" : "P5,S7x1 ; P17,S5x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "2",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "1",
    "billoflaborSectionIdentifier" : "4",
    "partNameIdentifier" : "1674",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "104",
    "laborItemPlaceholderDescription" : "Bottom Making-Compression Molded Phylon (CMP)-Buffing - CMP",
    "billoflaborLineItemComments" : "P12 - 1x3 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "3",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "3",
    "billoflaborSectionIdentifier" : "4",
    "partNameIdentifier" : "1674",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "108",
    "laborItemPlaceholderDescription" : "Bottom Making-Conventional Phylon-Trimming - Conventional Phylon Flash",
    "billoflaborLineItemComments" : "P14x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "7",
    "billoflaborSectionIdentifier" : "4",
    "partNameIdentifier" : "1674",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "112",
    "laborItemPlaceholderDescription" : "Bottom Making-Injection Phylon/Injection Unit (IP/IU)-Injection Phylon (Single)",
    "billoflaborLineItemComments" : "P12 - 1x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "9",
    "billoflaborSectionIdentifier" : "4",
    "partNameIdentifier" : "1674",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "113",
    "laborItemPlaceholderDescription" : "Bottom Making-Injection Phylon/Injection Unit (IP/IU)-Trimming IP/IU Flash & Runner",
    "billoflaborLineItemComments" : "P12 - 1x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "11",
    "billoflaborSectionIdentifier" : "4",
    "partNameIdentifier" : "1674",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "126",
    "laborItemPlaceholderDescription" : "Bottom Making-Rubber-Trimming - Rubber Component",
    "billoflaborLineItemComments" : "P16x2 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "2",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "13",
    "billoflaborSectionIdentifier" : "4",
    "partNameIdentifier" : "1674",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "127",
    "laborItemPlaceholderDescription" : "Bottom Making-Rubber-Trimming - Rubber Hand",
    "billoflaborLineItemComments" : "P16x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "15",
    "billoflaborSectionIdentifier" : "4",
    "partNameIdentifier" : "1674",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "179916",
    "laborItemPlaceholderDescription" : "Bottom Making-Conventional Phylon-Auto Mold Transfer (Midsole)",
    "billoflaborLineItemComments" : "P14x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "1",
    "billoflaborSectionIdentifier" : "6",
    "partNameIdentifier" : "1846",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "129",
    "laborItemPlaceholderDescription" : "Stockfitting-Attaching-Component",
    "billoflaborLineItemComments" : "P20,S8x3 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "3",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "3",
    "billoflaborSectionIdentifier" : "6",
    "partNameIdentifier" : "1846",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "130",
    "laborItemPlaceholderDescription" : "Stockfitting-Attaching-Deep Well Press",
    "billoflaborLineItemComments" : "P20,S9x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "5",
    "billoflaborSectionIdentifier" : "6",
    "partNameIdentifier" : "1846",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "131",
    "laborItemPlaceholderDescription" : "Stockfitting-Attaching-Fist Press",
    "billoflaborLineItemComments" : "P20,S10x4 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "4",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "7",
    "billoflaborSectionIdentifier" : "6",
    "partNameIdentifier" : "1846",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "137",
    "laborItemPlaceholderDescription" : "Stockfitting-Pre-Fit Prep-Cleaning - Midsole",
    "billoflaborLineItemComments" : "P20,S4x2 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "2",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "9",
    "billoflaborSectionIdentifier" : "6",
    "partNameIdentifier" : "1846",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "140",
    "laborItemPlaceholderDescription" : "Stockfitting-Pre-Fit Prep-Loading (Pre-Heat)",
    "billoflaborLineItemComments" : "P20,S10x2,S9x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "3",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "11",
    "billoflaborSectionIdentifier" : "6",
    "partNameIdentifier" : "1846",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "142",
    "laborItemPlaceholderDescription" : "Stockfitting-Pre-Fit Prep-Stamping",
    "billoflaborLineItemComments" : "P20,S11x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "13",
    "billoflaborSectionIdentifier" : "6",
    "partNameIdentifier" : "1846",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "143",
    "laborItemPlaceholderDescription" : "Stockfitting-Pre-Fit Prep-UV Treatment - Light",
    "billoflaborLineItemComments" : "P20,S14x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "15",
    "billoflaborSectionIdentifier" : "6",
    "partNameIdentifier" : "1846",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "145",
    "laborItemPlaceholderDescription" : "Stockfitting-Pre-Fit Prep-UV Treatment - Priming - Midsole",
    "billoflaborLineItemComments" : "P20,S10x1,S12x2 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "3",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "17",
    "billoflaborSectionIdentifier" : "6",
    "partNameIdentifier" : "1846",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "146",
    "laborItemPlaceholderDescription" : "Stockfitting-Pre-Fit Prep-Washing/Degreasing",
    "billoflaborLineItemComments" : "P12 - 1x1 ; P14x1 ; P20,S2x2,S2x1,S18x1,S19x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "7",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "19",
    "billoflaborSectionIdentifier" : "6",
    "partNameIdentifier" : "1846",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "148",
    "laborItemPlaceholderDescription" : "Stockfitting-Priming/Cementing-Component",
    "billoflaborLineItemComments" : "P20,S11x2,S6x2,S7x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "5",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "21",
    "billoflaborSectionIdentifier" : "6",
    "partNameIdentifier" : "1846",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "149",
    "laborItemPlaceholderDescription" : "Stockfitting-Priming/Cementing-Midsole",
    "billoflaborLineItemComments" : "P20,S4x2,S5x2 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "4",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "1",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "19",
    "laborItemPlaceholderDescription" : "Assembly-Assembly Prep-Cleaning Upper",
    "billoflaborLineItemComments" : "P22 - 1,S23x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "3",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "20",
    "laborItemPlaceholderDescription" : "Assembly-Assembly Prep-Gauge Marking",
    "billoflaborLineItemComments" : "P22 - 1,S22x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "5",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "23",
    "laborItemPlaceholderDescription" : "Assembly-Assembly Prep-Loading(Pre heat/Overhead Conveyer)",
    "billoflaborLineItemComments" : "P22 - 2,S33x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "7",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "26",
    "laborItemPlaceholderDescription" : "Assembly-Assembly Prep-Pen Marking",
    "billoflaborLineItemComments" : "P22 - 1,S21x4 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "4",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "9",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "28",
    "laborItemPlaceholderDescription" : "Assembly-Lasting-Strobel Hammering",
    "billoflaborLineItemComments" : "P22 - 1,S19x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "11",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "29",
    "laborItemPlaceholderDescription" : "Assembly-Assembly Prep-Strobel Stitching",
    "billoflaborLineItemComments" : "P22 - 1,S8x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "13",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "31",
    "laborItemPlaceholderDescription" : "Assembly-Attaching-Bottom, Upper",
    "billoflaborLineItemComments" : "P22 - 2,S29x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "15",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "33",
    "laborItemPlaceholderDescription" : "Assembly-Attaching-Deep Well Press",
    "billoflaborLineItemComments" : "P22 - 2,S30x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "17",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "103",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "40",
    "laborItemPlaceholderDescription" : "Assembly-Attaching-Sockliner Insert",
    "billoflaborLineItemComments" : "P22 - 2,S38x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "19",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "103",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "41",
    "laborItemPlaceholderDescription" : "Assembly-Attaching-Sockliner Press",
    "billoflaborLineItemComments" : "P22 - 2,S39x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "21",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "1617",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "44",
    "laborItemPlaceholderDescription" : "Assembly-Lacing-Final Adjustment - Lace",
    "billoflaborLineItemComments" : "P22 - 2,S44x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "23",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "1617",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "46",
    "laborItemPlaceholderDescription" : "Assembly-Lacing-Insert Component Cover",
    "billoflaborLineItemComments" : "P22 - 1,S15x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "25",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "1617",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "49",
    "laborItemPlaceholderDescription" : "Assembly-Lacing-Tightening/Loosening - Lace",
    "billoflaborLineItemComments" : "P22 - 1,S16x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "27",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "4774",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "51",
    "laborItemPlaceholderDescription" : "Assembly-Lasting-Delasting - All Types",
    "billoflaborLineItemComments" : "P22 - 2,S35x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "29",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "4774",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "52",
    "laborItemPlaceholderDescription" : "Assembly-Lasting-Heel/Seat Lasting",
    "billoflaborLineItemComments" : "P22 - 1,S13x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "31",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "4774",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "53",
    "laborItemPlaceholderDescription" : "Assembly-Lasting-Insert Last",
    "billoflaborLineItemComments" : "P22 - 1,S12x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "33",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "3562",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "64",
    "laborItemPlaceholderDescription" : "Assembly-Packing-Tissue Paper",
    "billoflaborLineItemComments" : "P22 - 2,S43x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "35",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "1674",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "65",
    "laborItemPlaceholderDescription" : "Assembly-Pre-Lasting-Backpart Molding-Hot",
    "billoflaborLineItemComments" : "P22 - 1,S3x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "37",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "4774",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "68",
    "laborItemPlaceholderDescription" : "Assembly-Pre-Lasting-Gather Stitch",
    "billoflaborLineItemComments" : "P22 - 1,S7x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "39",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "2326",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "75",
    "laborItemPlaceholderDescription" : "Assembly-Pre-Lasting-Toe Box Activation",
    "billoflaborLineItemComments" : "P22 - 1,S11x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "41",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "1674",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "78",
    "laborItemPlaceholderDescription" : "Assembly-Priming/Cementing-Bottom",
    "billoflaborLineItemComments" : "P22 - 2,S26x2,S28x2 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "4",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "43",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "103",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "85",
    "laborItemPlaceholderDescription" : "Assembly-Priming/Cementing-Sockliner",
    "billoflaborLineItemComments" : "P22 - 2,S37x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "45",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "3281",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "87",
    "laborItemPlaceholderDescription" : "Assembly-Priming/Cementing-Upper (Sidewall ≤2cm)",
    "billoflaborLineItemComments" : "P22 - 1,S25x1 ; P22 - 2,S27x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "2",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  }, {
    "billoflaborLineSortingSequence" : "47",
    "billoflaborSectionIdentifier" : "7",
    "partNameIdentifier" : "1674",
    "billoflaborSequenceOrderIdentifier" : "1",
    "billoflaborLineItemDescription" : "",
    "laborProcessIdentifier" : "170936",
    "laborItemPlaceholderDescription" : "Assembly-Pre-Lasting-Backpart Molding-Cold",
    "billoflaborLineItemComments" : "P22 - 1,S5x1 ;",
    "billoflaborObservedMinutes" : "0",
    "billoflaborCount" : "1",
    "billoflaborLength" : "0",
    "billoflaborCableCount" : "0",
    "billoflaborClipCount" : "0",
    "billoflaborPinCount" : "0",
    "billoflaborPressCount" : "0",
    "billoflaborShoeCount" : "0",
    "billoflaborSlitCount" : "0",
    "billoflaborRubberPreformCount" : "0",
    "billoflaborTrimCount" : "0",
    "billoflaborOutsourcedLaborCostCurrency" : "",
    "billoflaborOutsourcedLaborCost" : "0",
    "billoflaborInhouseIndicator" : "true",
    "billoflaborPCCSortOrder" : "0"
  } ]
}
)

db.bol.find("billoflaborLineSortingSequence":"47").pretty()

db.bol.find({"billoflaborLineSortingSequence":"47"}).pretty()


db.book.insert({"code":"001", "name":"Hujan2"})

db.book.insert({"code":"001","name":"Hujan","price": 45000,})

db.book.insert({"code":"001","name":"Hujan","price": 45000,
    "publisher":[{
"name": "Gramedia",
        "city":"Jakarta",
    }
    ]})